title: Carmel Drogin
logo: /assets/img/header.png
description:
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

# Add this to override the theme's default stylesheet
defaults:
  -
    scope:
      path: ""
    values:
      css: "/assets/css/style.scss"
